import os
from dataclasses import dataclass
from time import time
try:
    from .utils import check_dir
except ImportError:  # Script execution keeps filter/ as the import root.
    from utils import check_dir

TOKEN = ''
MODEL_MAX_LENGTH: dict = {
        "microsoft/codebert-base": 512,
        "bigcode/starencoder": 1024
    }


def get_model_max_length(base_model):
    if 'codebert-base' in base_model:
        return 512
    elif 'starencoder' in base_model:
        return 1024
    else:
        return 1024


@dataclass
class ModelConfig():
    max_thread_worker: int = 16
    # configs for persistence
    data_dir: str = 'data'
    dataset_cache: str = '.dataset_cache.json'
    dataset_cache_pkl: str = '.dataset_cache.pkl'
    dataset_cache_rev: str = '.dataset_cache_rev.json'
    funcs_covernum: str = 'funcs_covernum.json'
    start_t: float = time()
    # allias.txt are generated by
    # objdump -d --no-show-raw-insn vmlinux | grep __sanitizer_cov_trace_pc | cut -d: -f1 | addr2line -afi -e vmlinux > allias.txt
    allias: str = 'allias.txt'
    instru: str = 'instrumentations.json'
    pcs2funcs: str = 'pcs2funcs.json'


check_dir(ModelConfig.data_dir)
